<?php

namespace App\Http\Controllers\Backend\Settings;

use App\Http\Controllers\Controller;
use App\Models\PaymentGateway;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class PaymentGatewayController extends Controller
{
    public function index()
    {
        $gateways = PaymentGateway::all();

        return view('backend.payment_gateways.index', compact('gateways'));
    }

    public function create()
    {
        $currencies = [
            'usd',
            'eur',
            'gbp',
            'aed',
            'afn',
            'all',
            'amd',
            'ang',
            'aoa',
            'ars',
            'aud',
            'awg',
            'azn',
            'bam',
            'bbd',
            'bdt',
            'bgn',
            'bif',
            'bmd',
            'bnd',
            'bob',
            'brl',
            'bsd',
            'bwp',
            'bzd',
            'cad',
            'cdf',
            'chf',
            'clp',
            'cny',
            'cop',
            'crc',
            'cup',
            'cve',
            'czk',
            'djf',
            'dkk',
            'dop',
            'dzd',
            'egp',
            'etb',
            'fjd',
            'fkp',
            'gel',
            'ghs',
            'gip',
            'gmd',
            'gnf',
            'gtq',
            'gyd',
            'hkd',
            'hnl',
            'hrk',
            'htg',
            'huf',
            'idr',
            'ils',
            'inr',
            'isk',
            'jmd',
            'jpy',
            'kes',
            'kgs',
            'khr',
            'kmf',
            'krw',
            'kyd',
            'kzt',
            'lak',
            'lbp',
            'lkr',
            'lrd',
            'lsl',
            'mad',
            'mdl',
            'mga',
            'mkd',
            'mmk',
            'mnt',
            'mop',
            'mru',
            'mur',
            'mvr',
            'mwk',
            'mxn',
            'myr',
            'mzn',
            'nad',
            'ngn',
            'nio',
            'nok',
            'npr',
            'nzd',
            'pab',
            'pen',
            'pgk',
            'php',
            'pkr',
            'pln',
            'pyg',
            'qar',
            'ron',
            'rsd',
            'rub',
            'rwf',
            'sar',
            'sbd',
            'scr',
            'sek',
            'sgd',
            'shp',
            'sll',
            'sos',
            'srd',
            'std',
            'stn',
            'szl',
            'thb',
            'tjs',
            'top',
            'try',
            'ttd',
            'twd',
            'tzs',
            'uah',
            'ugx',
            'uyu',
            'uzs',
            'vnd',
            'vuv',
            'wst',
            'xaf',
            'xcd',
            'xof',
            'xpf',
            'yer',
            'zar',
            'zmw'
        ];
        return view('backend.payment_gateways.create', compact('currencies'));
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'api_key' => 'required|string',
            'api_secret' => 'nullable|string',
            'api_private' => 'nullable|string',
            'currency' => 'nullable|string|max:255',
            'webhook_secret' => 'nullable|string|max:255',

        ]);
        $validated['name'] = Str::lower($request->name);
        PaymentGateway::create($validated);

        return redirect()->route('admin.payment-gateways.index')->with('ok', 'Gateway ajouté avec succès.');
    }

    public function edit(PaymentGateway $paymentGateway)
    {
        $currencies = [
            'usd',
            'eur',
            'gbp',
            'aed',
            'afn',
            'all',
            'amd',
            'ang',
            'aoa',
            'ars',
            'aud',
            'awg',
            'azn',
            'bam',
            'bbd',
            'bdt',
            'bgn',
            'bif',
            'bmd',
            'bnd',
            'bob',
            'brl',
            'bsd',
            'bwp',
            'bzd',
            'cad',
            'cdf',
            'chf',
            'clp',
            'cny',
            'cop',
            'crc',
            'cup',
            'cve',
            'czk',
            'djf',
            'dkk',
            'dop',
            'dzd',
            'egp',
            'etb',
            'fjd',
            'fkp',
            'gel',
            'ghs',
            'gip',
            'gmd',
            'gnf',
            'gtq',
            'gyd',
            'hkd',
            'hnl',
            'hrk',
            'htg',
            'huf',
            'idr',
            'ils',
            'inr',
            'isk',
            'jmd',
            'jpy',
            'kes',
            'kgs',
            'khr',
            'kmf',
            'krw',
            'kyd',
            'kzt',
            'lak',
            'lbp',
            'lkr',
            'lrd',
            'lsl',
            'mad',
            'mdl',
            'mga',
            'mkd',
            'mmk',
            'mnt',
            'mop',
            'mru',
            'mur',
            'mvr',
            'mwk',
            'mxn',
            'myr',
            'mzn',
            'nad',
            'ngn',
            'nio',
            'nok',
            'npr',
            'nzd',
            'pab',
            'pen',
            'pgk',
            'php',
            'pkr',
            'pln',
            'pyg',
            'qar',
            'ron',
            'rsd',
            'rub',
            'rwf',
            'sar',
            'sbd',
            'scr',
            'sek',
            'sgd',
            'shp',
            'sll',
            'sos',
            'srd',
            'std',
            'stn',
            'szl',
            'thb',
            'tjs',
            'top',
            'try',
            'ttd',
            'twd',
            'tzs',
            'uah',
            'ugx',
            'uyu',
            'uzs',
            'vnd',
            'vuv',
            'wst',
            'xaf',
            'xcd',
            'xof',
            'xpf',
            'yer',
            'zar',
            'zmw'
        ];
        return view('backend.payment_gateways.edit', compact('paymentGateway', 'currencies'));
    }

    public function update(Request $request, PaymentGateway $paymentGateway)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'api_key' => 'required|string',
            'api_secret' => 'nullable|string',
            'api_private' => 'nullable|string',
            'currency' => 'nullable|string|max:255',
            'webhook_secret' => 'nullable|string|max:255',
        ]);
        $validated['name'] = Str::lower($request->name);
        $paymentGateway->update($validated);

        return redirect()->route('admin.payment-gateways.index')->with('ok', 'Gateway mis à jour avec succès.');
    }

    public function destroy(PaymentGateway $paymentGateway)
    {
        $paymentGateway->delete();
        return redirect()->route('admin.payment-gateways.index')->with('ok', 'Gateway supprimé avec succès.');
    }
}
